/*
  https://programmers.co.kr/learn/courses/30/lessons/59043
*/

SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME
FROM ANIMAL_INS, ANIMAL_OUTS
WHERE ANIMAL_INS.DATETIME > ANIMAL_OUTS.DATETIME AND ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
ORDER BY ANIMAL_INS.DATETIME