/*
  https://programmers.co.kr/learn/courses/30/lessons/59045
*/

SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_INS.NAME
FROM ANIMAL_INS, ANIMAL_OUTS
WHERE (ANIMAL_INS.SEX_UPON_INTAKE <> "Spayed Female" 
AND ANIMAL_INS.SEX_UPON_INTAKE <> "Neutered Male")
AND (ANIMAL_OUTS.SEX_UPON_OUTCOME = "Spayed Female" 
OR ANIMAL_OUTS.SEX_UPON_OUTCOME = "Neutered Male") 
AND ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
ORDER BY ANIMAL_INS.ANIMAL_ID ASC;